apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-pvc-build-
spec:
  entrypoint: kaniko-build-flow
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: kaniko-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: kaniko-build
          template: kaniko

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          MAX_RETRIES=5
          i=1

          while [  -le  ]; do
            echo "Attempt  of : Cloning repo..."
            git clone https://github.com/sid150/CheXpert.git /mnt/workspace && break
            echo "Git clone failed. Retrying in 5 seconds..."
            i=1
            sleep 5
          done

          if [ ! -d /mnt/workspace/.git ]; then
            echo "Git clone failed after  attempts."
            exit 1
          fi
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.kube-system.svc.cluster.local:5000/chexpert-app:staging-1.0.0
        - --destination=registry.kube-system.svc.cluster.local:5000/chexpert-app:canary-1.0.0
        - --destination=registry.kube-system.svc.cluster.local:5000/chexpert-app:production-1.0.0
        - --insecure
      volumeMounts:
        - name: workdir
          mountPath: /mnt/workspace
