name: eval_online
services:
  fastapi_server:
    build:
      context: ../fastapi_pt
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"  # for HTTP requests

  flask:
    build:
      context: ../chexpertService       # needs to be changed
      dockerfile: DockerFile
    container_name: flask
    ports:
      - "5050:5050"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  jupyter:
    build:
      context: ../jupyterServing
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    shm_size: 16g
    environment:
      - CHEXPERT_DATA_DIR=/mnt/dataset
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /home/cc/workspace:/home/jovyan/work
      - type: bind
        source: /mnt/object
        target: /mnt/dataset
        read_only: true
    command: bash -c "pip install alibi-detect numpy requests matplotlib && start-notebook.sh"