services:
  fastapi_server:
    build:
      context: ../fastAPI                # needs to be changed
      dockerfile: DockerFile
    container_name: fastapi_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"
#    volumes:
#      - ./fastApi/demoModel.pth:/app/demoModel.pth

  flask:
    build:
      context: ../chexpertService       # needs to be changed
      dockerfile: DockerFile
    container_name: flask
    ports:
      - "80:5000"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    shm_size: 16g
    volumes:
      - /home/cc/workspace:/home/jovyan/work
      - type: bind
        source: /mnt/object
        target: /mnt/dataset
        read_only: true
    command: >
      bash -c "pip install numpy requests matplotlib && start-notebook.sh"