global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'CheXpert'
    static_configs:
      - targets: ['fastapi_server:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]