{
 "title": "CheXpert Service Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CheXpert Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CheXpert Average Request Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "    1000 * rate(http_request_duration_seconds_sum{handler=\"/predict\", job=\"CheXpert\"}[1m]) / \n    rate(http_request_duration_seconds_count{handler=\"/predict\", job=\"CheXpert\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CheXpert request duration percentiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "Median"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "95th"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m]))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Requests Returning Error Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/predict\", status=\"4xx\"}[1m])",
     "legendFormat": "4XX"
    },
    {
     "expr": "rate(http_requests_total{handler=\"/predict\", status=\"5xx\"}[1m])",
     "legendFormat": "5XX"
    }
   ]
  }
 ]
}